package com.example.demo.model;

import java.util.ArrayList;
import java.util.List;

public class AlarmExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    public AlarmExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRencentAlarmsIncludeIsNull() {
            addCriterion("rencent_alarms_include is null");
            return (Criteria) this;
        }

        public Criteria andRencentAlarmsIncludeIsNotNull() {
            addCriterion("rencent_alarms_include is not null");
            return (Criteria) this;
        }

        public Criteria andRencentAlarmsIncludeEqualTo(Integer value) {
            addCriterion("rencent_alarms_include =", value, "rencentAlarmsInclude");
            return (Criteria) this;
        }

        public Criteria andRencentAlarmsIncludeNotEqualTo(Integer value) {
            addCriterion("rencent_alarms_include <>", value, "rencentAlarmsInclude");
            return (Criteria) this;
        }

        public Criteria andRencentAlarmsIncludeGreaterThan(Integer value) {
            addCriterion("rencent_alarms_include >", value, "rencentAlarmsInclude");
            return (Criteria) this;
        }

        public Criteria andRencentAlarmsIncludeGreaterThanOrEqualTo(Integer value) {
            addCriterion("rencent_alarms_include >=", value, "rencentAlarmsInclude");
            return (Criteria) this;
        }

        public Criteria andRencentAlarmsIncludeLessThan(Integer value) {
            addCriterion("rencent_alarms_include <", value, "rencentAlarmsInclude");
            return (Criteria) this;
        }

        public Criteria andRencentAlarmsIncludeLessThanOrEqualTo(Integer value) {
            addCriterion("rencent_alarms_include <=", value, "rencentAlarmsInclude");
            return (Criteria) this;
        }

        public Criteria andRencentAlarmsIncludeIn(List<Integer> values) {
            addCriterion("rencent_alarms_include in", values, "rencentAlarmsInclude");
            return (Criteria) this;
        }

        public Criteria andRencentAlarmsIncludeNotIn(List<Integer> values) {
            addCriterion("rencent_alarms_include not in", values, "rencentAlarmsInclude");
            return (Criteria) this;
        }

        public Criteria andRencentAlarmsIncludeBetween(Integer value1, Integer value2) {
            addCriterion("rencent_alarms_include between", value1, value2, "rencentAlarmsInclude");
            return (Criteria) this;
        }

        public Criteria andRencentAlarmsIncludeNotBetween(Integer value1, Integer value2) {
            addCriterion("rencent_alarms_include not between", value1, value2, "rencentAlarmsInclude");
            return (Criteria) this;
        }

        public Criteria andIntitalNotificationEvacuationIsNull() {
            addCriterion("intital_notification_evacuation is null");
            return (Criteria) this;
        }

        public Criteria andIntitalNotificationEvacuationIsNotNull() {
            addCriterion("intital_notification_evacuation is not null");
            return (Criteria) this;
        }

        public Criteria andIntitalNotificationEvacuationEqualTo(String value) {
            addCriterion("intital_notification_evacuation =", value, "intitalNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andIntitalNotificationEvacuationNotEqualTo(String value) {
            addCriterion("intital_notification_evacuation <>", value, "intitalNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andIntitalNotificationEvacuationGreaterThan(String value) {
            addCriterion("intital_notification_evacuation >", value, "intitalNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andIntitalNotificationEvacuationGreaterThanOrEqualTo(String value) {
            addCriterion("intital_notification_evacuation >=", value, "intitalNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andIntitalNotificationEvacuationLessThan(String value) {
            addCriterion("intital_notification_evacuation <", value, "intitalNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andIntitalNotificationEvacuationLessThanOrEqualTo(String value) {
            addCriterion("intital_notification_evacuation <=", value, "intitalNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andIntitalNotificationEvacuationLike(String value) {
            addCriterion("intital_notification_evacuation like", value, "intitalNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andIntitalNotificationEvacuationNotLike(String value) {
            addCriterion("intital_notification_evacuation not like", value, "intitalNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andIntitalNotificationEvacuationIn(List<String> values) {
            addCriterion("intital_notification_evacuation in", values, "intitalNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andIntitalNotificationEvacuationNotIn(List<String> values) {
            addCriterion("intital_notification_evacuation not in", values, "intitalNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andIntitalNotificationEvacuationBetween(String value1, String value2) {
            addCriterion("intital_notification_evacuation between", value1, value2, "intitalNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andIntitalNotificationEvacuationNotBetween(String value1, String value2) {
            addCriterion("intital_notification_evacuation not between", value1, value2, "intitalNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andEndingNotificationEvacuationIsNull() {
            addCriterion("ending_notification_evacuation is null");
            return (Criteria) this;
        }

        public Criteria andEndingNotificationEvacuationIsNotNull() {
            addCriterion("ending_notification_evacuation is not null");
            return (Criteria) this;
        }

        public Criteria andEndingNotificationEvacuationEqualTo(String value) {
            addCriterion("ending_notification_evacuation =", value, "endingNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andEndingNotificationEvacuationNotEqualTo(String value) {
            addCriterion("ending_notification_evacuation <>", value, "endingNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andEndingNotificationEvacuationGreaterThan(String value) {
            addCriterion("ending_notification_evacuation >", value, "endingNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andEndingNotificationEvacuationGreaterThanOrEqualTo(String value) {
            addCriterion("ending_notification_evacuation >=", value, "endingNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andEndingNotificationEvacuationLessThan(String value) {
            addCriterion("ending_notification_evacuation <", value, "endingNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andEndingNotificationEvacuationLessThanOrEqualTo(String value) {
            addCriterion("ending_notification_evacuation <=", value, "endingNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andEndingNotificationEvacuationLike(String value) {
            addCriterion("ending_notification_evacuation like", value, "endingNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andEndingNotificationEvacuationNotLike(String value) {
            addCriterion("ending_notification_evacuation not like", value, "endingNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andEndingNotificationEvacuationIn(List<String> values) {
            addCriterion("ending_notification_evacuation in", values, "endingNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andEndingNotificationEvacuationNotIn(List<String> values) {
            addCriterion("ending_notification_evacuation not in", values, "endingNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andEndingNotificationEvacuationBetween(String value1, String value2) {
            addCriterion("ending_notification_evacuation between", value1, value2, "endingNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andEndingNotificationEvacuationNotBetween(String value1, String value2) {
            addCriterion("ending_notification_evacuation not between", value1, value2, "endingNotificationEvacuation");
            return (Criteria) this;
        }

        public Criteria andDefaultEvacuationLengthIsNull() {
            addCriterion("default_evacuation_length is null");
            return (Criteria) this;
        }

        public Criteria andDefaultEvacuationLengthIsNotNull() {
            addCriterion("default_evacuation_length is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultEvacuationLengthEqualTo(String value) {
            addCriterion("default_evacuation_length =", value, "defaultEvacuationLength");
            return (Criteria) this;
        }

        public Criteria andDefaultEvacuationLengthNotEqualTo(String value) {
            addCriterion("default_evacuation_length <>", value, "defaultEvacuationLength");
            return (Criteria) this;
        }

        public Criteria andDefaultEvacuationLengthGreaterThan(String value) {
            addCriterion("default_evacuation_length >", value, "defaultEvacuationLength");
            return (Criteria) this;
        }

        public Criteria andDefaultEvacuationLengthGreaterThanOrEqualTo(String value) {
            addCriterion("default_evacuation_length >=", value, "defaultEvacuationLength");
            return (Criteria) this;
        }

        public Criteria andDefaultEvacuationLengthLessThan(String value) {
            addCriterion("default_evacuation_length <", value, "defaultEvacuationLength");
            return (Criteria) this;
        }

        public Criteria andDefaultEvacuationLengthLessThanOrEqualTo(String value) {
            addCriterion("default_evacuation_length <=", value, "defaultEvacuationLength");
            return (Criteria) this;
        }

        public Criteria andDefaultEvacuationLengthLike(String value) {
            addCriterion("default_evacuation_length like", value, "defaultEvacuationLength");
            return (Criteria) this;
        }

        public Criteria andDefaultEvacuationLengthNotLike(String value) {
            addCriterion("default_evacuation_length not like", value, "defaultEvacuationLength");
            return (Criteria) this;
        }

        public Criteria andDefaultEvacuationLengthIn(List<String> values) {
            addCriterion("default_evacuation_length in", values, "defaultEvacuationLength");
            return (Criteria) this;
        }

        public Criteria andDefaultEvacuationLengthNotIn(List<String> values) {
            addCriterion("default_evacuation_length not in", values, "defaultEvacuationLength");
            return (Criteria) this;
        }

        public Criteria andDefaultEvacuationLengthBetween(String value1, String value2) {
            addCriterion("default_evacuation_length between", value1, value2, "defaultEvacuationLength");
            return (Criteria) this;
        }

        public Criteria andDefaultEvacuationLengthNotBetween(String value1, String value2) {
            addCriterion("default_evacuation_length not between", value1, value2, "defaultEvacuationLength");
            return (Criteria) this;
        }

        public Criteria andManDownNotificationIsNull() {
            addCriterion("man_down_notification is null");
            return (Criteria) this;
        }

        public Criteria andManDownNotificationIsNotNull() {
            addCriterion("man_down_notification is not null");
            return (Criteria) this;
        }

        public Criteria andManDownNotificationEqualTo(String value) {
            addCriterion("man_down_notification =", value, "manDownNotification");
            return (Criteria) this;
        }

        public Criteria andManDownNotificationNotEqualTo(String value) {
            addCriterion("man_down_notification <>", value, "manDownNotification");
            return (Criteria) this;
        }

        public Criteria andManDownNotificationGreaterThan(String value) {
            addCriterion("man_down_notification >", value, "manDownNotification");
            return (Criteria) this;
        }

        public Criteria andManDownNotificationGreaterThanOrEqualTo(String value) {
            addCriterion("man_down_notification >=", value, "manDownNotification");
            return (Criteria) this;
        }

        public Criteria andManDownNotificationLessThan(String value) {
            addCriterion("man_down_notification <", value, "manDownNotification");
            return (Criteria) this;
        }

        public Criteria andManDownNotificationLessThanOrEqualTo(String value) {
            addCriterion("man_down_notification <=", value, "manDownNotification");
            return (Criteria) this;
        }

        public Criteria andManDownNotificationLike(String value) {
            addCriterion("man_down_notification like", value, "manDownNotification");
            return (Criteria) this;
        }

        public Criteria andManDownNotificationNotLike(String value) {
            addCriterion("man_down_notification not like", value, "manDownNotification");
            return (Criteria) this;
        }

        public Criteria andManDownNotificationIn(List<String> values) {
            addCriterion("man_down_notification in", values, "manDownNotification");
            return (Criteria) this;
        }

        public Criteria andManDownNotificationNotIn(List<String> values) {
            addCriterion("man_down_notification not in", values, "manDownNotification");
            return (Criteria) this;
        }

        public Criteria andManDownNotificationBetween(String value1, String value2) {
            addCriterion("man_down_notification between", value1, value2, "manDownNotification");
            return (Criteria) this;
        }

        public Criteria andManDownNotificationNotBetween(String value1, String value2) {
            addCriterion("man_down_notification not between", value1, value2, "manDownNotification");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterMandownIsNull() {
            addCriterion("dissappears_after_mandown is null");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterMandownIsNotNull() {
            addCriterion("dissappears_after_mandown is not null");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterMandownEqualTo(Integer value) {
            addCriterion("dissappears_after_mandown =", value, "dissappearsAfterMandown");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterMandownNotEqualTo(Integer value) {
            addCriterion("dissappears_after_mandown <>", value, "dissappearsAfterMandown");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterMandownGreaterThan(Integer value) {
            addCriterion("dissappears_after_mandown >", value, "dissappearsAfterMandown");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterMandownGreaterThanOrEqualTo(Integer value) {
            addCriterion("dissappears_after_mandown >=", value, "dissappearsAfterMandown");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterMandownLessThan(Integer value) {
            addCriterion("dissappears_after_mandown <", value, "dissappearsAfterMandown");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterMandownLessThanOrEqualTo(Integer value) {
            addCriterion("dissappears_after_mandown <=", value, "dissappearsAfterMandown");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterMandownIn(List<Integer> values) {
            addCriterion("dissappears_after_mandown in", values, "dissappearsAfterMandown");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterMandownNotIn(List<Integer> values) {
            addCriterion("dissappears_after_mandown not in", values, "dissappearsAfterMandown");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterMandownBetween(Integer value1, Integer value2) {
            addCriterion("dissappears_after_mandown between", value1, value2, "dissappearsAfterMandown");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterMandownNotBetween(Integer value1, Integer value2) {
            addCriterion("dissappears_after_mandown not between", value1, value2, "dissappearsAfterMandown");
            return (Criteria) this;
        }

        public Criteria andManDownMovementTriggerIsNull() {
            addCriterion("man_down_movement_trigger is null");
            return (Criteria) this;
        }

        public Criteria andManDownMovementTriggerIsNotNull() {
            addCriterion("man_down_movement_trigger is not null");
            return (Criteria) this;
        }

        public Criteria andManDownMovementTriggerEqualTo(Boolean value) {
            addCriterion("man_down_movement_trigger =", value, "manDownMovementTrigger");
            return (Criteria) this;
        }

        public Criteria andManDownMovementTriggerNotEqualTo(Boolean value) {
            addCriterion("man_down_movement_trigger <>", value, "manDownMovementTrigger");
            return (Criteria) this;
        }

        public Criteria andManDownMovementTriggerGreaterThan(Boolean value) {
            addCriterion("man_down_movement_trigger >", value, "manDownMovementTrigger");
            return (Criteria) this;
        }

        public Criteria andManDownMovementTriggerGreaterThanOrEqualTo(Boolean value) {
            addCriterion("man_down_movement_trigger >=", value, "manDownMovementTrigger");
            return (Criteria) this;
        }

        public Criteria andManDownMovementTriggerLessThan(Boolean value) {
            addCriterion("man_down_movement_trigger <", value, "manDownMovementTrigger");
            return (Criteria) this;
        }

        public Criteria andManDownMovementTriggerLessThanOrEqualTo(Boolean value) {
            addCriterion("man_down_movement_trigger <=", value, "manDownMovementTrigger");
            return (Criteria) this;
        }

        public Criteria andManDownMovementTriggerIn(List<Boolean> values) {
            addCriterion("man_down_movement_trigger in", values, "manDownMovementTrigger");
            return (Criteria) this;
        }

        public Criteria andManDownMovementTriggerNotIn(List<Boolean> values) {
            addCriterion("man_down_movement_trigger not in", values, "manDownMovementTrigger");
            return (Criteria) this;
        }

        public Criteria andManDownMovementTriggerBetween(Boolean value1, Boolean value2) {
            addCriterion("man_down_movement_trigger between", value1, value2, "manDownMovementTrigger");
            return (Criteria) this;
        }

        public Criteria andManDownMovementTriggerNotBetween(Boolean value1, Boolean value2) {
            addCriterion("man_down_movement_trigger not between", value1, value2, "manDownMovementTrigger");
            return (Criteria) this;
        }

        public Criteria andTriggerMovementManDownIsNull() {
            addCriterion("Trigger_movement_man_down is null");
            return (Criteria) this;
        }

        public Criteria andTriggerMovementManDownIsNotNull() {
            addCriterion("Trigger_movement_man_down is not null");
            return (Criteria) this;
        }

        public Criteria andTriggerMovementManDownEqualTo(Integer value) {
            addCriterion("Trigger_movement_man_down =", value, "triggerMovementManDown");
            return (Criteria) this;
        }

        public Criteria andTriggerMovementManDownNotEqualTo(Integer value) {
            addCriterion("Trigger_movement_man_down <>", value, "triggerMovementManDown");
            return (Criteria) this;
        }

        public Criteria andTriggerMovementManDownGreaterThan(Integer value) {
            addCriterion("Trigger_movement_man_down >", value, "triggerMovementManDown");
            return (Criteria) this;
        }

        public Criteria andTriggerMovementManDownGreaterThanOrEqualTo(Integer value) {
            addCriterion("Trigger_movement_man_down >=", value, "triggerMovementManDown");
            return (Criteria) this;
        }

        public Criteria andTriggerMovementManDownLessThan(Integer value) {
            addCriterion("Trigger_movement_man_down <", value, "triggerMovementManDown");
            return (Criteria) this;
        }

        public Criteria andTriggerMovementManDownLessThanOrEqualTo(Integer value) {
            addCriterion("Trigger_movement_man_down <=", value, "triggerMovementManDown");
            return (Criteria) this;
        }

        public Criteria andTriggerMovementManDownIn(List<Integer> values) {
            addCriterion("Trigger_movement_man_down in", values, "triggerMovementManDown");
            return (Criteria) this;
        }

        public Criteria andTriggerMovementManDownNotIn(List<Integer> values) {
            addCriterion("Trigger_movement_man_down not in", values, "triggerMovementManDown");
            return (Criteria) this;
        }

        public Criteria andTriggerMovementManDownBetween(Integer value1, Integer value2) {
            addCriterion("Trigger_movement_man_down between", value1, value2, "triggerMovementManDown");
            return (Criteria) this;
        }

        public Criteria andTriggerMovementManDownNotBetween(Integer value1, Integer value2) {
            addCriterion("Trigger_movement_man_down not between", value1, value2, "triggerMovementManDown");
            return (Criteria) this;
        }

        public Criteria andAccelerometerVectorManDownIsNull() {
            addCriterion("accelerometer_vector_man_down is null");
            return (Criteria) this;
        }

        public Criteria andAccelerometerVectorManDownIsNotNull() {
            addCriterion("accelerometer_vector_man_down is not null");
            return (Criteria) this;
        }

        public Criteria andAccelerometerVectorManDownEqualTo(Integer value) {
            addCriterion("accelerometer_vector_man_down =", value, "accelerometerVectorManDown");
            return (Criteria) this;
        }

        public Criteria andAccelerometerVectorManDownNotEqualTo(Integer value) {
            addCriterion("accelerometer_vector_man_down <>", value, "accelerometerVectorManDown");
            return (Criteria) this;
        }

        public Criteria andAccelerometerVectorManDownGreaterThan(Integer value) {
            addCriterion("accelerometer_vector_man_down >", value, "accelerometerVectorManDown");
            return (Criteria) this;
        }

        public Criteria andAccelerometerVectorManDownGreaterThanOrEqualTo(Integer value) {
            addCriterion("accelerometer_vector_man_down >=", value, "accelerometerVectorManDown");
            return (Criteria) this;
        }

        public Criteria andAccelerometerVectorManDownLessThan(Integer value) {
            addCriterion("accelerometer_vector_man_down <", value, "accelerometerVectorManDown");
            return (Criteria) this;
        }

        public Criteria andAccelerometerVectorManDownLessThanOrEqualTo(Integer value) {
            addCriterion("accelerometer_vector_man_down <=", value, "accelerometerVectorManDown");
            return (Criteria) this;
        }

        public Criteria andAccelerometerVectorManDownIn(List<Integer> values) {
            addCriterion("accelerometer_vector_man_down in", values, "accelerometerVectorManDown");
            return (Criteria) this;
        }

        public Criteria andAccelerometerVectorManDownNotIn(List<Integer> values) {
            addCriterion("accelerometer_vector_man_down not in", values, "accelerometerVectorManDown");
            return (Criteria) this;
        }

        public Criteria andAccelerometerVectorManDownBetween(Integer value1, Integer value2) {
            addCriterion("accelerometer_vector_man_down between", value1, value2, "accelerometerVectorManDown");
            return (Criteria) this;
        }

        public Criteria andAccelerometerVectorManDownNotBetween(Integer value1, Integer value2) {
            addCriterion("accelerometer_vector_man_down not between", value1, value2, "accelerometerVectorManDown");
            return (Criteria) this;
        }

        public Criteria andXAxisExceedsIsNull() {
            addCriterion("X_axis_exceeds is null");
            return (Criteria) this;
        }

        public Criteria andXAxisExceedsIsNotNull() {
            addCriterion("X_axis_exceeds is not null");
            return (Criteria) this;
        }

        public Criteria andXAxisExceedsEqualTo(Integer value) {
            addCriterion("X_axis_exceeds =", value, "xAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andXAxisExceedsNotEqualTo(Integer value) {
            addCriterion("X_axis_exceeds <>", value, "xAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andXAxisExceedsGreaterThan(Integer value) {
            addCriterion("X_axis_exceeds >", value, "xAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andXAxisExceedsGreaterThanOrEqualTo(Integer value) {
            addCriterion("X_axis_exceeds >=", value, "xAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andXAxisExceedsLessThan(Integer value) {
            addCriterion("X_axis_exceeds <", value, "xAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andXAxisExceedsLessThanOrEqualTo(Integer value) {
            addCriterion("X_axis_exceeds <=", value, "xAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andXAxisExceedsIn(List<Integer> values) {
            addCriterion("X_axis_exceeds in", values, "xAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andXAxisExceedsNotIn(List<Integer> values) {
            addCriterion("X_axis_exceeds not in", values, "xAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andXAxisExceedsBetween(Integer value1, Integer value2) {
            addCriterion("X_axis_exceeds between", value1, value2, "xAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andXAxisExceedsNotBetween(Integer value1, Integer value2) {
            addCriterion("X_axis_exceeds not between", value1, value2, "xAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andYAxisExceedsIsNull() {
            addCriterion("Y_axis_exceeds is null");
            return (Criteria) this;
        }

        public Criteria andYAxisExceedsIsNotNull() {
            addCriterion("Y_axis_exceeds is not null");
            return (Criteria) this;
        }

        public Criteria andYAxisExceedsEqualTo(Integer value) {
            addCriterion("Y_axis_exceeds =", value, "yAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andYAxisExceedsNotEqualTo(Integer value) {
            addCriterion("Y_axis_exceeds <>", value, "yAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andYAxisExceedsGreaterThan(Integer value) {
            addCriterion("Y_axis_exceeds >", value, "yAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andYAxisExceedsGreaterThanOrEqualTo(Integer value) {
            addCriterion("Y_axis_exceeds >=", value, "yAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andYAxisExceedsLessThan(Integer value) {
            addCriterion("Y_axis_exceeds <", value, "yAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andYAxisExceedsLessThanOrEqualTo(Integer value) {
            addCriterion("Y_axis_exceeds <=", value, "yAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andYAxisExceedsIn(List<Integer> values) {
            addCriterion("Y_axis_exceeds in", values, "yAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andYAxisExceedsNotIn(List<Integer> values) {
            addCriterion("Y_axis_exceeds not in", values, "yAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andYAxisExceedsBetween(Integer value1, Integer value2) {
            addCriterion("Y_axis_exceeds between", value1, value2, "yAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andYAxisExceedsNotBetween(Integer value1, Integer value2) {
            addCriterion("Y_axis_exceeds not between", value1, value2, "yAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andZAxisExceedsIsNull() {
            addCriterion("Z_axis_exceeds is null");
            return (Criteria) this;
        }

        public Criteria andZAxisExceedsIsNotNull() {
            addCriterion("Z_axis_exceeds is not null");
            return (Criteria) this;
        }

        public Criteria andZAxisExceedsEqualTo(Integer value) {
            addCriterion("Z_axis_exceeds =", value, "zAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andZAxisExceedsNotEqualTo(Integer value) {
            addCriterion("Z_axis_exceeds <>", value, "zAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andZAxisExceedsGreaterThan(Integer value) {
            addCriterion("Z_axis_exceeds >", value, "zAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andZAxisExceedsGreaterThanOrEqualTo(Integer value) {
            addCriterion("Z_axis_exceeds >=", value, "zAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andZAxisExceedsLessThan(Integer value) {
            addCriterion("Z_axis_exceeds <", value, "zAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andZAxisExceedsLessThanOrEqualTo(Integer value) {
            addCriterion("Z_axis_exceeds <=", value, "zAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andZAxisExceedsIn(List<Integer> values) {
            addCriterion("Z_axis_exceeds in", values, "zAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andZAxisExceedsNotIn(List<Integer> values) {
            addCriterion("Z_axis_exceeds not in", values, "zAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andZAxisExceedsBetween(Integer value1, Integer value2) {
            addCriterion("Z_axis_exceeds between", value1, value2, "zAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andZAxisExceedsNotBetween(Integer value1, Integer value2) {
            addCriterion("Z_axis_exceeds not between", value1, value2, "zAxisExceeds");
            return (Criteria) this;
        }

        public Criteria andPanicNotificationIsNull() {
            addCriterion("panic_notification is null");
            return (Criteria) this;
        }

        public Criteria andPanicNotificationIsNotNull() {
            addCriterion("panic_notification is not null");
            return (Criteria) this;
        }

        public Criteria andPanicNotificationEqualTo(String value) {
            addCriterion("panic_notification =", value, "panicNotification");
            return (Criteria) this;
        }

        public Criteria andPanicNotificationNotEqualTo(String value) {
            addCriterion("panic_notification <>", value, "panicNotification");
            return (Criteria) this;
        }

        public Criteria andPanicNotificationGreaterThan(String value) {
            addCriterion("panic_notification >", value, "panicNotification");
            return (Criteria) this;
        }

        public Criteria andPanicNotificationGreaterThanOrEqualTo(String value) {
            addCriterion("panic_notification >=", value, "panicNotification");
            return (Criteria) this;
        }

        public Criteria andPanicNotificationLessThan(String value) {
            addCriterion("panic_notification <", value, "panicNotification");
            return (Criteria) this;
        }

        public Criteria andPanicNotificationLessThanOrEqualTo(String value) {
            addCriterion("panic_notification <=", value, "panicNotification");
            return (Criteria) this;
        }

        public Criteria andPanicNotificationLike(String value) {
            addCriterion("panic_notification like", value, "panicNotification");
            return (Criteria) this;
        }

        public Criteria andPanicNotificationNotLike(String value) {
            addCriterion("panic_notification not like", value, "panicNotification");
            return (Criteria) this;
        }

        public Criteria andPanicNotificationIn(List<String> values) {
            addCriterion("panic_notification in", values, "panicNotification");
            return (Criteria) this;
        }

        public Criteria andPanicNotificationNotIn(List<String> values) {
            addCriterion("panic_notification not in", values, "panicNotification");
            return (Criteria) this;
        }

        public Criteria andPanicNotificationBetween(String value1, String value2) {
            addCriterion("panic_notification between", value1, value2, "panicNotification");
            return (Criteria) this;
        }

        public Criteria andPanicNotificationNotBetween(String value1, String value2) {
            addCriterion("panic_notification not between", value1, value2, "panicNotification");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterPanicIsNull() {
            addCriterion("dissappears_after_panic is null");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterPanicIsNotNull() {
            addCriterion("dissappears_after_panic is not null");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterPanicEqualTo(Integer value) {
            addCriterion("dissappears_after_panic =", value, "dissappearsAfterPanic");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterPanicNotEqualTo(Integer value) {
            addCriterion("dissappears_after_panic <>", value, "dissappearsAfterPanic");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterPanicGreaterThan(Integer value) {
            addCriterion("dissappears_after_panic >", value, "dissappearsAfterPanic");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterPanicGreaterThanOrEqualTo(Integer value) {
            addCriterion("dissappears_after_panic >=", value, "dissappearsAfterPanic");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterPanicLessThan(Integer value) {
            addCriterion("dissappears_after_panic <", value, "dissappearsAfterPanic");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterPanicLessThanOrEqualTo(Integer value) {
            addCriterion("dissappears_after_panic <=", value, "dissappearsAfterPanic");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterPanicIn(List<Integer> values) {
            addCriterion("dissappears_after_panic in", values, "dissappearsAfterPanic");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterPanicNotIn(List<Integer> values) {
            addCriterion("dissappears_after_panic not in", values, "dissappearsAfterPanic");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterPanicBetween(Integer value1, Integer value2) {
            addCriterion("dissappears_after_panic between", value1, value2, "dissappearsAfterPanic");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterPanicNotBetween(Integer value1, Integer value2) {
            addCriterion("dissappears_after_panic not between", value1, value2, "dissappearsAfterPanic");
            return (Criteria) this;
        }

        public Criteria andDalilyNotificationIsNull() {
            addCriterion("dalily_notification is null");
            return (Criteria) this;
        }

        public Criteria andDalilyNotificationIsNotNull() {
            addCriterion("dalily_notification is not null");
            return (Criteria) this;
        }

        public Criteria andDalilyNotificationEqualTo(String value) {
            addCriterion("dalily_notification =", value, "dalilyNotification");
            return (Criteria) this;
        }

        public Criteria andDalilyNotificationNotEqualTo(String value) {
            addCriterion("dalily_notification <>", value, "dalilyNotification");
            return (Criteria) this;
        }

        public Criteria andDalilyNotificationGreaterThan(String value) {
            addCriterion("dalily_notification >", value, "dalilyNotification");
            return (Criteria) this;
        }

        public Criteria andDalilyNotificationGreaterThanOrEqualTo(String value) {
            addCriterion("dalily_notification >=", value, "dalilyNotification");
            return (Criteria) this;
        }

        public Criteria andDalilyNotificationLessThan(String value) {
            addCriterion("dalily_notification <", value, "dalilyNotification");
            return (Criteria) this;
        }

        public Criteria andDalilyNotificationLessThanOrEqualTo(String value) {
            addCriterion("dalily_notification <=", value, "dalilyNotification");
            return (Criteria) this;
        }

        public Criteria andDalilyNotificationLike(String value) {
            addCriterion("dalily_notification like", value, "dalilyNotification");
            return (Criteria) this;
        }

        public Criteria andDalilyNotificationNotLike(String value) {
            addCriterion("dalily_notification not like", value, "dalilyNotification");
            return (Criteria) this;
        }

        public Criteria andDalilyNotificationIn(List<String> values) {
            addCriterion("dalily_notification in", values, "dalilyNotification");
            return (Criteria) this;
        }

        public Criteria andDalilyNotificationNotIn(List<String> values) {
            addCriterion("dalily_notification not in", values, "dalilyNotification");
            return (Criteria) this;
        }

        public Criteria andDalilyNotificationBetween(String value1, String value2) {
            addCriterion("dalily_notification between", value1, value2, "dalilyNotification");
            return (Criteria) this;
        }

        public Criteria andDalilyNotificationNotBetween(String value1, String value2) {
            addCriterion("dalily_notification not between", value1, value2, "dalilyNotification");
            return (Criteria) this;
        }

        public Criteria andAlarmResponsePanelIsNull() {
            addCriterion("alarm_response_panel is null");
            return (Criteria) this;
        }

        public Criteria andAlarmResponsePanelIsNotNull() {
            addCriterion("alarm_response_panel is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmResponsePanelEqualTo(Boolean value) {
            addCriterion("alarm_response_panel =", value, "alarmResponsePanel");
            return (Criteria) this;
        }

        public Criteria andAlarmResponsePanelNotEqualTo(Boolean value) {
            addCriterion("alarm_response_panel <>", value, "alarmResponsePanel");
            return (Criteria) this;
        }

        public Criteria andAlarmResponsePanelGreaterThan(Boolean value) {
            addCriterion("alarm_response_panel >", value, "alarmResponsePanel");
            return (Criteria) this;
        }

        public Criteria andAlarmResponsePanelGreaterThanOrEqualTo(Boolean value) {
            addCriterion("alarm_response_panel >=", value, "alarmResponsePanel");
            return (Criteria) this;
        }

        public Criteria andAlarmResponsePanelLessThan(Boolean value) {
            addCriterion("alarm_response_panel <", value, "alarmResponsePanel");
            return (Criteria) this;
        }

        public Criteria andAlarmResponsePanelLessThanOrEqualTo(Boolean value) {
            addCriterion("alarm_response_panel <=", value, "alarmResponsePanel");
            return (Criteria) this;
        }

        public Criteria andAlarmResponsePanelIn(List<Boolean> values) {
            addCriterion("alarm_response_panel in", values, "alarmResponsePanel");
            return (Criteria) this;
        }

        public Criteria andAlarmResponsePanelNotIn(List<Boolean> values) {
            addCriterion("alarm_response_panel not in", values, "alarmResponsePanel");
            return (Criteria) this;
        }

        public Criteria andAlarmResponsePanelBetween(Boolean value1, Boolean value2) {
            addCriterion("alarm_response_panel between", value1, value2, "alarmResponsePanel");
            return (Criteria) this;
        }

        public Criteria andAlarmResponsePanelNotBetween(Boolean value1, Boolean value2) {
            addCriterion("alarm_response_panel not between", value1, value2, "alarmResponsePanel");
            return (Criteria) this;
        }

        public Criteria andZoneBreachTimeIsNull() {
            addCriterion("zone_breach_time is null");
            return (Criteria) this;
        }

        public Criteria andZoneBreachTimeIsNotNull() {
            addCriterion("zone_breach_time is not null");
            return (Criteria) this;
        }

        public Criteria andZoneBreachTimeEqualTo(Integer value) {
            addCriterion("zone_breach_time =", value, "zoneBreachTime");
            return (Criteria) this;
        }

        public Criteria andZoneBreachTimeNotEqualTo(Integer value) {
            addCriterion("zone_breach_time <>", value, "zoneBreachTime");
            return (Criteria) this;
        }

        public Criteria andZoneBreachTimeGreaterThan(Integer value) {
            addCriterion("zone_breach_time >", value, "zoneBreachTime");
            return (Criteria) this;
        }

        public Criteria andZoneBreachTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("zone_breach_time >=", value, "zoneBreachTime");
            return (Criteria) this;
        }

        public Criteria andZoneBreachTimeLessThan(Integer value) {
            addCriterion("zone_breach_time <", value, "zoneBreachTime");
            return (Criteria) this;
        }

        public Criteria andZoneBreachTimeLessThanOrEqualTo(Integer value) {
            addCriterion("zone_breach_time <=", value, "zoneBreachTime");
            return (Criteria) this;
        }

        public Criteria andZoneBreachTimeIn(List<Integer> values) {
            addCriterion("zone_breach_time in", values, "zoneBreachTime");
            return (Criteria) this;
        }

        public Criteria andZoneBreachTimeNotIn(List<Integer> values) {
            addCriterion("zone_breach_time not in", values, "zoneBreachTime");
            return (Criteria) this;
        }

        public Criteria andZoneBreachTimeBetween(Integer value1, Integer value2) {
            addCriterion("zone_breach_time between", value1, value2, "zoneBreachTime");
            return (Criteria) this;
        }

        public Criteria andZoneBreachTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("zone_breach_time not between", value1, value2, "zoneBreachTime");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterZoneBreachIsNull() {
            addCriterion("dissappears_after_zone_breach is null");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterZoneBreachIsNotNull() {
            addCriterion("dissappears_after_zone_breach is not null");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterZoneBreachEqualTo(Integer value) {
            addCriterion("dissappears_after_zone_breach =", value, "dissappearsAfterZoneBreach");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterZoneBreachNotEqualTo(Integer value) {
            addCriterion("dissappears_after_zone_breach <>", value, "dissappearsAfterZoneBreach");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterZoneBreachGreaterThan(Integer value) {
            addCriterion("dissappears_after_zone_breach >", value, "dissappearsAfterZoneBreach");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterZoneBreachGreaterThanOrEqualTo(Integer value) {
            addCriterion("dissappears_after_zone_breach >=", value, "dissappearsAfterZoneBreach");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterZoneBreachLessThan(Integer value) {
            addCriterion("dissappears_after_zone_breach <", value, "dissappearsAfterZoneBreach");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterZoneBreachLessThanOrEqualTo(Integer value) {
            addCriterion("dissappears_after_zone_breach <=", value, "dissappearsAfterZoneBreach");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterZoneBreachIn(List<Integer> values) {
            addCriterion("dissappears_after_zone_breach in", values, "dissappearsAfterZoneBreach");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterZoneBreachNotIn(List<Integer> values) {
            addCriterion("dissappears_after_zone_breach not in", values, "dissappearsAfterZoneBreach");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterZoneBreachBetween(Integer value1, Integer value2) {
            addCriterion("dissappears_after_zone_breach between", value1, value2, "dissappearsAfterZoneBreach");
            return (Criteria) this;
        }

        public Criteria andDissappearsAfterZoneBreachNotBetween(Integer value1, Integer value2) {
            addCriterion("dissappears_after_zone_breach not between", value1, value2, "dissappearsAfterZoneBreach");
            return (Criteria) this;
        }

        public Criteria andRemoveFromAlarmIsNull() {
            addCriterion("remove_from_alarm is null");
            return (Criteria) this;
        }

        public Criteria andRemoveFromAlarmIsNotNull() {
            addCriterion("remove_from_alarm is not null");
            return (Criteria) this;
        }

        public Criteria andRemoveFromAlarmEqualTo(Integer value) {
            addCriterion("remove_from_alarm =", value, "removeFromAlarm");
            return (Criteria) this;
        }

        public Criteria andRemoveFromAlarmNotEqualTo(Integer value) {
            addCriterion("remove_from_alarm <>", value, "removeFromAlarm");
            return (Criteria) this;
        }

        public Criteria andRemoveFromAlarmGreaterThan(Integer value) {
            addCriterion("remove_from_alarm >", value, "removeFromAlarm");
            return (Criteria) this;
        }

        public Criteria andRemoveFromAlarmGreaterThanOrEqualTo(Integer value) {
            addCriterion("remove_from_alarm >=", value, "removeFromAlarm");
            return (Criteria) this;
        }

        public Criteria andRemoveFromAlarmLessThan(Integer value) {
            addCriterion("remove_from_alarm <", value, "removeFromAlarm");
            return (Criteria) this;
        }

        public Criteria andRemoveFromAlarmLessThanOrEqualTo(Integer value) {
            addCriterion("remove_from_alarm <=", value, "removeFromAlarm");
            return (Criteria) this;
        }

        public Criteria andRemoveFromAlarmIn(List<Integer> values) {
            addCriterion("remove_from_alarm in", values, "removeFromAlarm");
            return (Criteria) this;
        }

        public Criteria andRemoveFromAlarmNotIn(List<Integer> values) {
            addCriterion("remove_from_alarm not in", values, "removeFromAlarm");
            return (Criteria) this;
        }

        public Criteria andRemoveFromAlarmBetween(Integer value1, Integer value2) {
            addCriterion("remove_from_alarm between", value1, value2, "removeFromAlarm");
            return (Criteria) this;
        }

        public Criteria andRemoveFromAlarmNotBetween(Integer value1, Integer value2) {
            addCriterion("remove_from_alarm not between", value1, value2, "removeFromAlarm");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alarm
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 04 20:56:48 ICT 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alarm
     *
     * @mbg.generated Fri Jun 04 20:56:48 ICT 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}