package com.example.demo.model;

public class Items {
	private Integer id;
	public Items(String name, Integer userId) {
		super();
		this.name = name;
		this.userId = userId;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column items.name
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column items.user_id
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	private Integer userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column items.id
	 * @return  the value of items.id
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column items.id
	 * @param id  the value for items.id
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column items.name
	 * @return  the value of items.name
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column items.name
	 * @param name  the value for items.name
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column items.user_id
	 * @return  the value of items.user_id
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column items.user_id
	 * @param userId  the value for items.user_id
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}