package com.example.demo.model;

import java.util.Date;

public class Users {

	public Users(String name, Date birthday) {
		super();
		this.name = name;
		this.birthday = birthday;
	}

	public Users(Integer id, String name, Date birthday) {
		super();
		this.id = id;
		this.name = name;
		this.birthday = birthday;
	}

	public Users(Integer id, String name) {
		super();
		this.id = id;
		this.name = name;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.id
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.name
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.birthday
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	private Date birthday;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.id
	 * @return  the value of users.id
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.id
	 * @param id  the value for users.id
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.name
	 * @return  the value of users.name
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.name
	 * @param name  the value for users.name
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.birthday
	 * @return  the value of users.birthday
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.birthday
	 * @param birthday  the value for users.birthday
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}
}