package com.example.demo.mapper;

import com.example.demo.model.Items;
import com.example.demo.model.ItemsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ItemsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table items
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	long countByExample(ItemsExample example);

	int deleteByExample(ItemsExample example);

	int deleteByPrimaryKey(Integer id);

	int insert(Items record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table items
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	int insertSelective(Items record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table items
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	List<Items> selectByExample(ItemsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table items
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	Items selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table items
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	int updateByExampleSelective(@Param("record") Items record, @Param("example") ItemsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table items
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	int updateByExample(@Param("record") Items record, @Param("example") ItemsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table items
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	int updateByPrimaryKeySelective(Items record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table items
	 * @mbg.generated  Wed Jun 02 16:06:48 ICT 2021
	 */
	int updateByPrimaryKey(Items record);
}